


# FROM node
FROM  node:20.9.0-alpine3.18

WORKDIR /frontend

#  Copy all local files to image:
COPY . .

# When build images:
RUN npm i -g pnpm
RUN pnpm i

# When build containers:
# CMD npm start
CMD [ "npm", "start" ]

# Optional:
EXPOSE 5173

# --------------------------------
# $ cd / frontend
# $ docker build -t frontend .
# $ docker run -p 5173:5173 --name frontend frontend
# $ docker run -d -p 5173:5173 --name frontend frontend # daemon !! arka planda çalıştır
# $ Browser: http://localhost:8000