


# FROM node
FROM  node:20.9.0-alpine3.18

WORKDIR /frontend

#  Copy all local files to image:
COPY . .

# When build images:

RUN npm install
# When build containers:
# CMD npm start
CMD [ "npm", "start" ]

# Optional:
EXPOSE 8000

# --------------------------------
# $ cd / frontend
# $ docker build -t frontend .
# $ docker run -p 8000:8000 --name frontend frontend
# $ docker run -d -p 8000:8000 --name frontend frontend # daemon !! arka planda çalıştır
# $ Browser: http://localhost:8000